Update Publish GHA

diff --git a/.github/workflows/publish.yaml b/.github/workflows/publish.yaml
--- a/.github/workflows/publish.yaml
+++ b/.github/workflows/publish.yaml
@@ -1,41 +1,47 @@
-name: Create and publish CI/CD Docker image
+name: Create and publish a Docker image
 
 on:
   push:
     tags:
-      - '[6-9].[0-9].[0-9]-[0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9]_[0-9]'
+      - '*'
+    branches: [ continuous-release-exo ]
 env:
-  DOCKERHUB_IMAGE_NAME: 'exoplatform/jitsi'
-
+  BRANCH_BUILD_TAGS: "nightly"
 jobs:
-  build-and-push-image:
+  parse-docker-build-env:
+    name: 'Parse Docker Build Environment'
     runs-on: ubuntu-latest
-
+    outputs:
+      buildTags: ${{ steps.detect-push-event.outputs.buildTags }}
     steps:
-      - name: Checkout repository
-        uses: actions/checkout@v4
-
-      - name: Set up Docker Buildx
-        uses: docker/setup-buildx-action@v3
-
-      - name: Log in to Docker Hub
-        uses: docker/login-action@v3
-        with:
-          username: ${{ secrets.DOCKER_USERNAME }}
-          password: ${{ secrets.DOCKER_PASSWORD }}
-
-      - name: Extract metadata (tags, labels) for Docker
-        id: meta
-        uses: docker/metadata-action@v5
-        with:
-          images: ${{ env.DOCKERHUB_IMAGE_NAME }}
-
-      - name: Build and push Docker image to Dockerhub
-        uses: docker/build-push-action@v6
-        with:
-          context: .
-          push: true
-          tags: ${{ steps.meta.outputs.tags }}
-          labels: ${{ steps.meta.outputs.labels }}
-          provenance: true
-          sbom: true
+      - name: Check if push is a tag or branch
+        id: detect-push-event
+        run: |
+          if [[ $GITHUB_REF == refs/tags/* ]]; then
+            TAG="${GITHUB_REF#refs/tags/}"
+            echo "This is a tag push ($TAG)"
+            if [[ ! "$TAG" =~ ^[6-9]\.[0-9]\.[0-9]-[0-9]{8}([0-9]{2})?_[0-9]$ ]]; then
+              echo "❌ Invalid tag format: $TAG"
+              exit 1
+            fi
+            echo "Building docker tag: ${GITHUB_REF#refs/tags/}"
+            echo "buildTags=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT
+          elif [[ $GITHUB_REF == refs/heads/* ]]; then
+            echo "This is a branch push (${GITHUB_REF#refs/heads/})"
+            echo "Building docker tags: ${{ env.BRANCH_BUILD_TAGS }}"
+            echo "buildTags=${{ env.BRANCH_BUILD_TAGS }}" >> $GITHUB_OUTPUT
+          else
+            echo "Unknown push type"
+            exit 1
+          fi
+  build-dockerhub-image:
+    name: "Build Docker Images to DockerHub Registry"
+    runs-on: ubuntu-latest
+    needs: parse-docker-build-env
+    steps:
+    - uses: exo-actions/buildDockerImage-action@v1
+      with:
+        dockerImage: "exoplatform/jitsi"
+        dockerImageTag: ${{ needs.parse-docker-build-env.outputs.buildTags }}
+        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
+        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
